### ISSUE TITLE
Merge with VintageousPlus?

### ISSUE THREAD

**Issue by trishume** [gerardroche/Vintageous#2]
@gerardroche hey would you consider merging with https://github.com/trishume/VintageousPlus ?

I know you mentioned in https://github.com/guillermooo/Vintageous/issues/1096 that you don't want to deviate from stock vim. I'm willing to give up deviating from stock vim by default for the greater benefit of collaboration and there being one clearly maintained better fork. 

If I add anything that deviates from stock vim I'll add it behind a setting that is off by default. In my fork I already have a simple mechanism for adding functionality that can be enabled/disabled by a setting.

If you're open to this I don't know if you have strong preferences as to which direction the merge should go. I would suggest you merge in to mine, I have a name and a repo that isn't set up as a fork (so PRs work correctly), but I'm open to alternatives. I could merge into yours or we could merge into an organization.

Random logistics notes:
- I think the name should be clearly based off of "Vintageous" so that people know it is a fork that is strictly better and don't worry about which they should use.
- The merge will probably be riddled with conflicts, I'm willing to do the work to resolve them, but in order to resolve them I do need to know the name to go with.
- If you don't want to deal with other people committing to master I'm willing to do all my work as PRs

**Comment by gerardroche** [comment]
I was going to ask you if you wanted to combine efforts too. A setting disabled by default for plus functionality is good for me.

How did you setup your repository? Create a new one, clone Vintageous, and then push it to the new one? I've been looking for an easy way to merge the pull requests from the original repository into mine but there doesn't seem to be one. But I think it best to deal with any pr's and merges before doing any more big changes. I'll see what merge conflict I get if I try merge yours with mine, see if I can resolve it and then worry about renaming the package later because I still intend on moving all the root directory .py files into a subfolder, removing more dead code, and generally reorganise things to make it easier to refactor and get some idea of what can be done to improve things.

I think creating an organisation for the project would be best.

On the name. I'm not sure about VintageousPlus. I'd rather not get it confused with vim-plus. If others are like me they won't like the idea of non standard vim operations. The name alone could deter them. As far keeping the name Vintageous. I'm also not sure we need to keep it as part of the name either. For example, Guillermo didn't feel the need to be tied to the name. We can add a "vintageous" tag to the package in Package Control and mention it being a fork in the description. When people search for alternatives they will search for "vim".

As far as committing to master. I don't mind commits to master. I usually branch and merge back to master when ready but I've been hacking away on master because it was just me and I'm trying to get the main cleanup repository done. As long as the tests keep passing I'm happy.

**Comment by trishume** [comment]
@gerardroche Cool. An organization sounds good.

I was mainly wanting to attract the people who search for `Vintageous` in the Sublime Package Control install menu, which doesn't search descriptions or tags, but shows descriptions. They'd see both Vintageous and a new package with a description that clearly says that it is strictly better.

I'm not sure how much people search for "vim" vs. "Vintageous". Vim is what they want, but there's quite a number of references to Vintageous on the internet, and people who already know that is what they want. Something with Vim in the name would probably work pretty well too.

As for what I did to set up my repo and merge PRs: I created a new empty repo, cloned Vintageous, added the empty repo as a remote and pushed maser to it. Then I used [hub](https://hub.github.com) to merge the PRs from Vintageous into my repo.

As for merge strategies I think the best approach might be to create a branch off of my repo, do a find+replace of `VintageousPlus` with `Vintageous`, then merge. Although I forget if Git merging detects conflicts when you change something conflicting and then change it back. Then after the merge rename everything to whatever new name we choose. It's unfortunate that all the imports in the package are done in an absolute way so that the code is tied to the package name.

Here's some name possibilities, using the Sublime package convention of UpperCamelCase:

- NeoVintageous: like NeoVim, has the right connotations, NeoVim is also a stricty better fork that is cleaned up and maintained. This one's my favourite.
- Advintageous: pun on Advantageous, shows up in Sublime search because of substring. Downside: not obviously a vim plugin
- SublimeVim
- VimEmulator
- Vimic: your`vim_mimic` but contracted
- VimMimic
- OpenVim: to contrast with Six, which may be better, but isn't open source
- VimLime

**Comment by gerardroche** [comment]
I didn't think about search via the PC menu.

NeoVintageous or NeoVim :) I actually use neovim over vim. I love that it's so compatible with vim, I only had to make trivial changes to my vimrc and it was an improved anyways.

Is it fair to use the name neovim? It might not even be accepted to the package control channel. Plus the neovim organisation is taken. So I think yeah, NeoVintageous. It's good. I like it.

lowercase vs CamelCase

neovintageous vs NeoVintageous

[neovim](https://github.com/neovim/neovim) tends to use lowercase consistently. OS's are case insensitive, urls too.

**Comment by trishume** [comment]
Great. I know it's written `neovim` very often, but there's two reasons I chose the casing I did:

- Looking at https://packagecontrol.io it seems that the convention is that package names are capitalized, either `UpperCamel` or `Title Case`. I don't like the idea of having the package name written differently in the code than the title, hence why I didn't include a space. It seems reasonable to not deviate from package naming convention without a clear reason.
- I keep creating projects where the canonical name is lowercase (e.g [syntect](https://github.com/trishume/syntect)) and every time I regret it since it looks weird when I write it at the start of an english sentence and I constantly feel obliged to write it in backticks like `syntect` instead of just syntect.

**Comment by gerardroche** [comment]
I had the same issue with the start of sentences too. But just now I see neovim capitalises it at the start of sentences and in other similar contexts. Syntect looks correct. But I agree in some contexts it can be a bit of nightmare. I have a package called phpunitkit, which until just this minute I could never decide how to type it. Phpunitkit is the way I'm typing from now on when it starts a sentence otherwise phpunitkit.

Spaces are definitely out. File paths with spaces are nightmare to deal with on virtually all OS's.

I was going to say I'm good either way because I couldn't remember why I'm against camel case package names: https://www.python.org/dev/peps/pep-0008/#package-and-module-names.

**Comment by trishume** [comment]
Yah I know it doesn't match the python convention, but if I have to choose between matching the Sublime Package convention and the Python one, I'm inclined to choose the Package Control one since everyone sees that instead of the Python one which only maintainers see. Out of the top ~200 Sublime packages, only one has a lowercase name (sublimelint). Also I like the camel case distinguishing the word parts, and adding an underscore wouldn't be like neovim.

**Comment by gerardroche** [comment]
No underscore. neovintageous or NeoVintageous. I'll let you flip a coin :)

**Comment by trishume** [comment]
I say NeoVintageous. I'll create an organization and add you to it.

**Comment by trishume** [comment]
here it is: https://github.com/NeoVintageous I even quickly made a logo since organizations have a profile picture.

**Comment by gerardroche** [comment]
:+1: 

Issues and discussion can be moved to [NeoVintageous](https://github.com/NeoVintageous/NeoVintageous/issues/1).

**Comment by karamfil** [comment]
Hi Guys, 

Just wanted to say one HUGE THANK YOU!
